app = "audioperduny"  # Your app name

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[mounts]
  source = "audio_data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true