app = "perduny-bot"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  # Add or ensure this section is correctly formatted as an array of tables
  [[services.checks]]
    port = 8080
    path = "/healthz"
    interval = "10s"
    timeout = "2s"
    # You can add other check parameters here if needed, e.g.:
    # grace_period = "5s"
    # restart_limit = 3

[[http_service.checks]]
  interval = "15s"
  timeout = "5s"
  path = "/healthz"

[mounts]
  source="my_audio_volume"
  destination="/app/audio_messages" # This should match your AUDIO_STORAGE path