app = "audioperduny"  # Your app name

[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[mounts]
  source = "audio_data"
  destination = "/data"