app = "perduny-bot"

[http_service]
  internal_port = 8080
  force_https = true

[[http_service.checks]]
  interval = "15s"
  timeout = "5s"
  path = "/healthz"

[mounts]
  source="my_audio_volume"
  destination="/app/audio_messages" # This should match your AUDIO_STORAGE path